### ISSUE TITLE
`mago self-update` errors if `paths` contains invalid path

### ISSUE THREAD

**Issue by bendavies** [carthage-software/mago#117]
### 🐞 Describe the Bug

```sh
❯ sudo mago self-update
ERROR Failed to canonicalize path `"src/Owsy"`: No such file or directory (os error 2)
```

as an aside, `src/Owsy` was put in `mago.toml` by `mago init` since it is in `composer.json`. however that directory no longer exists.

### 🔄 Steps to Reproduce

1. invalid path in `paths`
2. `sudo mago self-update`

### ⚙️ Configuration (mago.toml)

```toml
[source]
paths = ["src/BindHQ", "src/Owsy", "src/", "tests/functional/BindHQ", "tests/unit/Owsy", "tests/unit/BindHQ", "spec/Owsy/"]
```

### 📜 Command Output

```shell
❯ sudo MAGO_LOG=trace mago self-update
DEBUG Configuration specifies 10 threads.
DEBUG Configuration specifies a stack size of 37748736 bytes.
ERROR Failed to canonicalize path `"src/Owsy"`: No such file or directory (os error 2
```

### 📂 PHP Code Sample (If Applicable)

```php

```

### 🖥️ Operating System

Linux

### 📦 How did you install Mago?

Prebuilt Binary (download from GitHub)
