### ISSUE TITLE
More control over method chaining

### ISSUE THREAD

**Issue by innocenzi** [carthage-software/mago#122]
## Description

I'm reopening a more specific issue so we can track this specifically. At Tempest, we would like to move away from php-cs-fixer, but we can't yet because the formatting is not consistent enough with what we want.

The issue is that Mago sometimes break, and sometimes doesn't break method chaining calls.

## Ideal solution

**Ideally, Mago would let us preserve the current method chaining**. If we're having two method calls in one line, it keeps it this way. If we break lines, it keeps it this way.

This is the simplest way for now, because Mago can't tell if a specific snippet of code is more readable—there will always be exceptions.

I would like Mago to introduce `preserve_method_chain_breaking_style`. When `true`, this option would stop adding or removing new lines in method chains. This would be in-line with our php-cs-fixer configuration.

## Examples

**Before**

```php
return new CreateTableStatement('user_permissions')
  ->primary()
  ->belongsTo('user_permissions.user_id', 'users.id')
  ->belongsTo('user_permissions.permission_id', 'permissions.id');
```

**After**

```php
return new CreateTableStatement('user_permissions')->primary()->belongsTo('user_permissions.user_id', 'users.id')->belongsTo(
    'user_permissions.permission_id',
    'permissions.id',
);
```

---

**Before**

```php
$item = $this->getCachePool()
    ->getItem($key)
    ->set($value);
```

**After**

```php
$item = $this->getCachePool()->getItem($key)->set($value);
```

---

**Before**

```php
$appNamespace = str($this->ask('Which namespace do you wish to use?', default: $defaultAppNamespace))
      ->trim('\\')
      ->append('\\')
      ->toString();
```

**After**

```php
$appNamespace = str($this->ask('Which namespace do you wish to use?', default: $defaultAppNamespace))->trim('\\')->append('\\')->toString();
```

## Config

```toml
# Mago configuration file
# For more information, see https://mago.carthage.software/#/getting-started/configuration
php_version = "8.4.0"

[source]
paths = ["src"]
includes = ["vendor"]
excludes = []

[format]
print_width = 180
tab_width = 4
use_tabs = false
always_break_named_arguments_list = false
always_break_attribute_named_argument_lists = false
space_after_not_operator = true
null_type_hint = "question"

[linter]
default_plugins = true
plugins = ["symfony", "laravel", "php-unit"]
```
