### ISSUE TITLE
More control over argument list breaking

### ISSUE THREAD

**Issue by innocenzi** [carthage-software/mago#123]
## Description

I'm opening another specific issue related to my last feedback so we can track this specifically. 

That issue is that Mago sometimes break, and sometimes doesn't break argument lists in method calls.

## Ideal solution

**Ideally, Mago would let us preserve the current line breaks**. If the argument list is split on new lines, it keeps it this way. If it's all on one line, same.

This is the simplest way for now, because Mago can't tell if a specific snippet of code is more readable—there will always be exceptions.

I would like Mago to introduce `preserve_argument_list_line_breaks`. When `true`, this option would stop adding or removing new lines in argument lists. This would be in-line with our php-cs-fixer configuration.

## Examples

**Before**

```php
new UserPermission(
    user: $this,
    permission: $permission,
)->save();
```

**After**

```php
new UserPermission(user: $this, permission: $permission)->save();
```

---

**Before**

```php
$this->console->keyValue('Global cache', match ($this->cacheConfig->enable) {
    true => '<style="bold fg-green">ENABLED</style>',
    false => '<style="bold fg-red">FORCEFULLY DISABLED</style>',
    default => '<style="bold fg-gray">DISABLED</style>',
});
```

**After**

```php
$this->console->keyValue(
    'Global cache',
    match ($this->cacheConfig->enable) {
        true => '<style="bold fg-green">ENABLED</style>',
        false => '<style="bold fg-red">FORCEFULLY DISABLED</style>',
        default => '<style="bold fg-gray">DISABLED</style>',
    },
);
```

---

**Before**

```php
$this->pool = $this->cacheConfig->projectCachePool ?? new FilesystemAdapter(
    directory: path($this->cacheConfig->directory, 'project')->toString(),
);
```

**After**

```php
 $this->pool = $this->cacheConfig->projectCachePool ?? new FilesystemAdapter(directory: path($this->cacheConfig->directory, 'project')->toString());
```

---

**Before**

```php
$this->expectExceptionObject(
    new CommandHandlerNotFound($command),
);
```

**After**

```php
$this->expectExceptionObject(new CommandHandlerNotFound($command));
```

## Config

```toml
# Mago configuration file
# For more information, see https://mago.carthage.software/#/getting-started/configuration
php_version = "8.4.0"

[source]
paths = ["src"]
includes = ["vendor"]
excludes = []

[format]
print_width = 180
tab_width = 4
use_tabs = false
always_break_named_arguments_list = false
always_break_attribute_named_argument_lists = false
space_after_not_operator = true
null_type_hint = "question"

[linter]
default_plugins = true
plugins = ["symfony", "laravel", "php-unit"]
```
