### ISSUE TITLE
`preserve_breaking_*` rules sometimes don't work

### ISSUE THREAD

**Issue by innocenzi** [carthage-software/mago#128]
## Description

I found some cases where `preserve_breaking_parameter_list` and `preserve_breaking_member_access_chain` don't seem to work:

---

**Before**

```php
$permission = Permission::query()->whereField('name', $name)->first();
```

**After**

```php
$permission = Permission::query()
    ->whereField('name', $name)
    ->first();
```

---

**Before**

```php
$this->writeln(implode(PHP_EOL, $complete->complete(
    $command,
    $argumentBag,
    $current,
)));
```

**After**

```php
$this->writeln(implode(
    PHP_EOL,
    $complete->complete(
        $command,
        $argumentBag,
        $current,
    ),
));
```

---

**Before**

```php
$this->renderer = new ChoiceRenderer(multiple: $multiple, default: (string) $default);
```

**After**

```php
$this->renderer = new ChoiceRenderer(
    multiple: $multiple,
    default: (string) $default,
);
```

---

**Before**

```php
return new ImmutableString($string)
    ->truncate($this->maxLineCharacters - 1 - $maxLineOffset, end: '…') // -1 is for the ellipsis
    ->toString();
```

**After**

```php
return new ImmutableString($string)
    ->truncate(($this->maxLineCharacters - 1) - $maxLineOffset, end: '…')
    // -1 is for the ellipsis
    ->toString();
```

## Config

```toml
php_version = "8.4.0"

[source]
paths = ["src"]
includes = ["vendor"]
excludes = []

[format]
print_width = 180
tab_width = 4
use_tabs = false
space_after_not_operator = true
null_type_hint = "question"
space_before_arrow_function_params = true
preserve_breaking_member_access_chain = true
preserve_breaking_argument_list = true
preserve_breaking_array_like = true
preserve_breaking_parameter_list = true
preserve_breaking_attribute_list = true

[linter]
default_plugins = true
plugins = ["symfony", "php-unit"]
```
