### ISSUE TITLE
`preserve_breaking_conditional_expression` doesn't always preserve ternary formatting

### ISSUE THREAD

**Issue by innocenzi** [carthage-software/mago#133]
Here are some examples:

**Before**

```php
$this->now = $now instanceof DateTimeInterface
    ? DateTimeImmutable::createFromInterface($now)
    : new DateTimeImmutable($now);
```

**After**

```php
$this->now = ($now instanceof DateTimeInterface) ? DateTimeImmutable::createFromInterface($now) : new DateTimeImmutable($now);
```

---

**Before**

```php
private function getControls(): array
{
    return [
        ...($this->bufferEnabled ? [
            'esc' => 'select',
        ] : [
            '/' => 'filter',
            'space' => 'select',
        ]),
        '↑' => 'up',
        '↓' => 'down',
        'enter' => $this->options->getSelectedOptions() === []
            ? 'skip'
            : 'confirm',
        'ctrl+c' => 'cancel',
    ];
}
```

**After**

```php
private function getControls(): array
{
    return [
        ...(
            $this->bufferEnabled
                ? [
                    'esc' => 'select',
                ] : [
                    '/' => 'filter',
                    'space' => 'select',
                ]
        ),
        '↑' => 'up',
        '↓' => 'down',
        'enter' => $this->options->getSelectedOptions() === [] ? 'skip' : 'confirm',
        'ctrl+c' => 'cancel',
    ];
}
```

## Config

➜  ./vendor/bin/mago --version
mago 0.19.0

```toml
php_version = "8.4.0"

[source]
paths = ["src"]
includes = ["vendor"]
excludes = []

[format]
print_width = 180
tab_width = 4
use_tabs = false
space_after_not_operator = true
null_type_hint = "question"
space_before_arrow_function_params = true
preserve_breaking_member_access_chain = true
preserve_breaking_argument_list = true
preserve_breaking_array_like = true
preserve_breaking_parameter_list = true
preserve_breaking_attribute_list = true

[linter]
default_plugins = true
plugins = ["symfony", "php-unit"]

```
