### ISSUE TITLE
`preserve_breaking_argument_list` doesn't preserve argument list formatting

### ISSUE THREAD

**Issue by innocenzi** [carthage-software/mago#135]
**Before**

```php
$this->renderer = new ChoiceRenderer(multiple: false, default: $default);
```

**After**

```php
$this->renderer = new ChoiceRenderer(
    multiple: false,
    default: $default,
);
```

---

**Before**

```php
$this->sockets = stream_socket_pair(domain: STREAM_PF_UNIX, type: STREAM_SOCK_STREAM, protocol: STREAM_IPPROTO_IP);
```

**After**

```php
$this->sockets = stream_socket_pair(
    domain: STREAM_PF_UNIX,
    type: STREAM_SOCK_STREAM,
    protocol: STREAM_IPPROTO_IP,
);
```

## Config

```toml
php_version = "8.4.0"

[source]
paths = ["src"]
includes = ["vendor"]
excludes = []

[format]
print_width = 180
tab_width = 4
use_tabs = false
space_after_not_operator = true
null_type_hint = "question"
space_before_arrow_function_params = true
preserve_breaking_member_access_chain = true
preserve_breaking_argument_list = true
preserve_breaking_array_like = true
preserve_breaking_parameter_list = true
preserve_breaking_attribute_list = true
preserve_breaking_conditional_expression = true

[linter]
default_plugins = true
plugins = ["symfony", "php-unit"]

```
