### ISSUE TITLE
Unexpected line break on assignation

### ISSUE THREAD

**Issue by innocenzi** [carthage-software/mago#136]
Not sure how to describe that, but I don't expect the line break here, especially since my `print_width` is large enough.

**Before**

```php
$answerAsString = arr($answers)
  ->map(fn (Option $option) => $option->displayValue)
  ->join(', ', ' and ')
  ->trim()
  ->toString() ?: 'no option';
```

**After**

```php
$answerAsString =
  arr($answers)
      ->map(fn (Option $option) => $option->displayValue)
      ->join(', ', ' and ')
      ->trim()
      ->toString() ?: 'no option';
```
---

**Before**

```php
$longestCommandName = max(
    arr($commands)
        ->flatMap(fn (array $group) => $group)
        ->map(fn (ConsoleCommand $command) => mb_strlen($command->getName()))
        ->toArray(),
) + 4;
```

**After**

```php
$longestCommandName =
    max(
        arr($commands)
            ->flatMap(fn (array $group) => $group)
            ->map(fn (ConsoleCommand $command) => mb_strlen($command->getName()))
            ->toArray(),
    ) + 4;
```

---

**Before**

```php
$content .= PHP_EOL . arr($validationErrors)
  ->map(fn (string $error) => "  <style=\"fg-yellow\">{$error}</style>")
  ->implode(PHP_EOL)
  ->append(PHP_EOL)
  ->toString();
```

**After**

```php
$content .=
    PHP_EOL .
    arr($validationErrors)
        ->map(fn (string $error) => "  <style=\"fg-yellow\">{$error}</style>")
        ->implode(PHP_EOL)
        ->append(PHP_EOL)
        ->toString();
```

---

```toml
php_version = "8.4.0"

[source]
paths = ["src"]
includes = ["vendor"]
excludes = []

[format]
print_width = 180
tab_width = 4
use_tabs = false
space_after_not_operator = true
null_type_hint = "question"
space_before_arrow_function_params = true
preserve_breaking_member_access_chain = true
preserve_breaking_argument_list = true
preserve_breaking_array_like = true
preserve_breaking_parameter_list = true
preserve_breaking_attribute_list = true
preserve_breaking_conditional_expression = true

[linter]
default_plugins = true
plugins = ["symfony", "php-unit"]
```
