### ISSUE TITLE
Unexpected line break in empty array

### ISSUE THREAD

**Issue by innocenzi** [carthage-software/mago#137]
We have this default configuration file:

```php
<?php

declare(strict_types=1);

use Tempest\CommandBus\CommandBusConfig;

return new CommandBusConfig(
    middleware: [
        // Add your command bus middleware here.
    ],
);
```

Mago 0.19.0 formats it this way:

```php
<?php

declare(strict_types=1);

use Tempest\CommandBus\CommandBusConfig;

return new CommandBusConfig(
    middleware: [
        // Add your command bus middleware here.

    ],
);
```

Note the line break after the comment.

```toml
php_version = "8.4.0"

[source]
paths = ["src"]
includes = ["vendor"]
excludes = []

[format]
print_width = 180
tab_width = 4
use_tabs = false
space_after_not_operator = true
null_type_hint = "question"
space_before_arrow_function_params = true
preserve_breaking_member_access_chain = true
preserve_breaking_argument_list = true
preserve_breaking_array_like = true
preserve_breaking_parameter_list = true
preserve_breaking_attribute_list = true
preserve_breaking_conditional_expression = true

[linter]
default_plugins = true
plugins = ["symfony", "php-unit"]
```
