### ISSUE TITLE
Unecessary line break during long-line assignation

### ISSUE THREAD

**Issue by innocenzi** [carthage-software/mago#138]
I spotted a situation where I assume my `print_width` of 180 causes a line break during the assignation of a very long string.

I believe this should not happen because it doesn't help with readability.

**Before**

```php
$safariFix = '<script nomodule>!function(){var e=document,t=e.createElement("script");if(!("noModule"in t)&&"onbeforeload"in t){var n=!1;e.addEventListener("beforeload",(function(e){if(e.target===t)n=!0;else if(!e.target.hasAttribute("nomodule")||!n)return;e.preventDefault()}),!0),t.type="module",t.src=".",e.head.appendChild(t),t.remove()}}();</script>';
$bundleLoader = '<script type="module">!function(){try{new Function("m","return import(m)")}catch(o){console.warn("vite: loading legacy build because dynamic import is unsupported, syntax error above should be ignored");var e=document.getElementById("vite-legacy-polyfill"),n=document.createElement("script");n.src=e.src,n.onload=function(){var entries=Array.prototype.slice.call(document.querySelectorAll("[data-vite-legacy]"),0);entries.forEach(function(entry){System.import(entry.getAttribute("data-src")).catch(console.error)})},document.body.appendChild(n)}}();</script>';
```

**After**

```php
$safariFix =
                '<script nomodule>!function(){var e=document,t=e.createElement("script");if(!("noModule"in t)&&"onbeforeload"in t){var n=!1;e.addEventListener("beforeload",(function(e){if(e.target===t)n=!0;else if(!e.target.hasAttribute("nomodule")||!n)return;e.preventDefault()}),!0),t.type="module",t.src=".",e.head.appendChild(t),t.remove()}}();</script>';
$bundleLoader =
                '<script type="module">!function(){try{new Function("m","return import(m)")}catch(o){console.warn("vite: loading legacy build because dynamic import is unsupported, syntax error above should be ignored");var e=document.getElementById("vite-legacy-polyfill"),n=document.createElement("script");n.src=e.src,n.onload=function(){var entries=Array.prototype.slice.call(document.querySelectorAll("[data-vite-legacy]"),0);entries.forEach(function(entry){System.import(entry.getAttribute("data-src")).catch(console.error)})},document.body.appendChild(n)}}();</script>';
```

---

Mago v0.19.1

```toml
php_version = "8.4.0"

[source]
paths = ["src"]
includes = ["vendor"]
excludes = []

[format]
print_width = 180
tab_width = 4
use_tabs = false
space_after_not_operator = true
null_type_hint = "question"
space_before_arrow_function_params = true
always_break_named_arguments_list = false
preserve_breaking_member_access_chain = true
preserve_breaking_argument_list = true
preserve_breaking_array_like = true
preserve_breaking_parameter_list = true
preserve_breaking_attribute_list = true
preserve_breaking_conditional_expression = true

[linter]
default_plugins = true
plugins = ["symfony", "php-unit"]
```
