### ISSUE TITLE
Case where `preserve_breaking_argument_list` is ignored

### ISSUE THREAD

**Issue by innocenzi** [carthage-software/mago#144]
I have `preserve_breaking_argument_list` enabled, but the following gets formatted by Mago v0.19.1. Note that it also moves the `;` after the comment.

I think it's a bug because Mago expect a line comment to be `//`, not `/*`, but it's still a valid comment. If I modify the comment to use `//`, it works as expected.

**Before**

```php
return in_array($name, $caseNames, strict: true); /** @phpstan-ignore-line function.impossibleType ( prevent to always evaluate to true/false as in enum context the result is predictable ) */
```

**After**

```php
return in_array(
    $name,
    $caseNames,
    strict: true,
) /** @phpstan-ignore-line function.impossibleType ( prevent to always evaluate to true/false as in enum context the result is predictable ) */;
```

**Config**

```toml
php_version = "8.4.0"

[source]
paths = ["src"]
includes = ["vendor"]
excludes = [
  "./vendor/symfony/cache/Traits/ValueWrapper.php",
  "./vendor/composer",
]

[format]
print_width = 180
tab_width = 4
use_tabs = false
space_after_not_operator = true
null_type_hint = "question"
space_before_arrow_function_params = true
always_break_named_arguments_list = false
preserve_breaking_member_access_chain = true
preserve_breaking_argument_list = true
preserve_breaking_array_like = true
preserve_breaking_parameter_list = true
preserve_breaking_attribute_list = true
preserve_breaking_conditional_expression = true
```
