### ISSUE TITLE
Unexpected formatting PHP tag inside a PHP-HTML file

### ISSUE THREAD

**Issue by innocenzi** [carthage-software/mago#149]
I have a `file.view.php` with the following content:

```php
<?php /** @var \Tempest\View\GenericView $this */ ?>

<html lang="en">
<head>
    <title>Ellison | Tempest</title>
    <!-- ... -->
```

Mago formats it as follows:

```php
<?php  /** @var \Tempest\View\GenericView $this */
?>

<html lang="en">
<head>
    <title>Ellison | Tempest</title>
    <!-- ... -->
```

Using the following config and Mago v0.19.3:

```toml
php_version = "8.4.0"

[source]
paths = ["app"]
includes = ["vendor"]
excludes = [
  "./vendor/symfony/cache/Traits/ValueWrapper.php",
  "./vendor/composer",
]

[format]
print_width = 180
tab_width = 4
use_tabs = false
space_after_not_operator = true
null_type_hint = "question"
space_before_arrow_function_params = true
always_break_named_arguments_list = false
preserve_breaking_member_access_chain = true
preserve_breaking_argument_list = true
preserve_breaking_array_like = true
preserve_breaking_parameter_list = true
preserve_breaking_attribute_list = true
preserve_breaking_conditional_expression = true
```
