### ISSUE TITLE
Class methods with attributes are not separated by a new line

### ISSUE THREAD

**Issue by innocenzi** [carthage-software/mago#151]
The following class should get the `serialize` and `unserialize` methods separated by an empty line, but this is currently not the case:

```php
<?php

namespace App\Analytics;

use App\Support\StoredEvents\HasCreatedAtDate;
use App\Support\StoredEvents\ShouldBeStored;
use DateTimeImmutable;
use Symfony\Component\Uid\Uuid;

final class PageVisited implements ShouldBeStored, HasCreatedAtDate
{
    public string $uuid;

    public function __construct(
        public string $url,
        public DateTimeImmutable $visitedAt,
        public string $ip,
        public string $userAgent,
        public string $raw,
    ) {
        $this->uuid = Uuid::v4()->toString();
    }

    public DateTimeImmutable $createdAt {
        get => $this->visitedAt;
    }

    #[\Override]
    public function serialize(): string
    {
        return json_encode([
            'uuid' => $this->uuid,
            'url' => $this->url,
            'visitedAt' => $this->visitedAt->format('c'),
            'ip' => $this->ip,
            'userAgent' => $this->userAgent,
            'raw' => $this->raw,
            'uri' => $this->url,
        ]);
    }
    #[\Override]
    public static function unserialize(string $payload): self
    {
        $data = json_decode($payload, true);

        $self = new self(
            url: $data['url'],
            visitedAt: new DateTimeImmutable($data['visitedAt']),
            ip: $data['ip'],
            userAgent: $data['userAgent'],
            raw: $data['raw'],
        );

        $self->uuid = $data['uuid'];

        return $self;
    }
}
```

I am using the following config:

```toml
php_version = "8.4.0"

[source]
paths = ["app"]
includes = ["vendor"]
excludes = [
  "./vendor/symfony/cache/Traits/ValueWrapper.php",
  "./vendor/composer",
]

[format]
print_width = 180
tab_width = 4
use_tabs = false
space_after_not_operator = true
null_type_hint = "question"
space_before_arrow_function_params = true
always_break_named_arguments_list = false
preserve_breaking_member_access_chain = true
preserve_breaking_argument_list = true
preserve_breaking_array_like = true
preserve_breaking_parameter_list = true
preserve_breaking_attribute_list = true
preserve_breaking_conditional_expression = true
```
