### ISSUE TITLE
Formatter: bug reformatting heredoc

### ISSUE THREAD

**Issue by bendavies** [carthage-software/mago#155]
### 🐞 Describe the Bug

the following heredoc is being formatted incorrectly, with whitespace removed around a variable.

`{$table} t` becomes `{$table}t`

### 🔄 Steps to Reproduce

`mago fmt`

### ⚙️ Configuration (mago.toml)

```toml
# Mago configuration file
# For more information, see https://mago.carthage.software/#/getting-started/configuration
php_version = "8.3.0"

[source]
paths = ["src/", "tests/", "spec/", "migrations/"]
includes = ["vendor"]
excludes = []

[format]
print_width = 180
tab_width = 4
use_tabs = false
null_type_hint = "question"
preserve_breaking_argument_list = true
preserve_breaking_array_like = true
preserve_breaking_attribute_list = true
preserve_breaking_conditional_expression = true
preserve_breaking_member_access_chain = true
preserve_breaking_parameter_list = true

[linter]
default_plugins = true
plugins = ["symfony", "php-unit"]
```

### 📜 Command Output

```shell
nothing useful in trace.
```

### 📂 PHP Code Sample (If Applicable)

```php
$tables = ['credit_memo', 'invoice', 'refund', 'vendor_payment', 'payment', 'deposit', 'journal', 'bill', 'bill_credit'];

\array_map([$this, 'addSql'], Vec\map($tables, static function ($table) {
    return <<<SQL
        update amount as a set posted_at = t.posted_at
          from entry e, {$table} t
         where e.id = a.entry_id
           and e.id = t.entry_id;
        SQL;
}));
```

is being formatted to:

```php
$tables = ['credit_memo', 'invoice', 'refund', 'vendor_payment', 'payment', 'deposit', 'journal', 'bill', 'bill_credit'];

\array_map(
    [$this, 'addSql'],
    Vec\map($tables, static function ($table) {
        return <<<SQL
        update amount as a set posted_at = t.posted_at
          from entry e, {$table}t
         where e.id = a.entry_id
           and e.id = t.entry_id;
        SQL;
    }),
);
```

### 🖥️ Operating System

Linux

### 📦 How did you install Mago?

Homebrew (brew install mago)
