### ISSUE TITLE
formatting: double formatting

### ISSUE THREAD

**Issue by bendavies** [carthage-software/mago#157]
### 🐞 Describe the Bug

`fmt` is not indempotent for the following code

### 🔄 Steps to Reproduce

1. mago fmt
2. mago fmt

both produce a diff

### ⚙️ Configuration (mago.toml)

```toml
# Mago configuration file
# For more information, see https://mago.carthage.software/#/getting-started/configuration
php_version = "8.3.0"

[source]
paths = ["src/", "tests/", "spec/", "migrations/"]
includes = ["vendor"]
excludes = []

[format]
print_width = 180
tab_width = 4
use_tabs = false
null_type_hint = "question"
preserve_breaking_argument_list = true
preserve_breaking_array_like = true
preserve_breaking_attribute_list = true
preserve_breaking_conditional_expression = true
preserve_breaking_member_access_chain = true
preserve_breaking_parameter_list = true

[linter]
default_plugins = true
plugins = ["symfony", "php-unit"]
```

### 📜 Command Output

```shell
mago fmt
```

### 📂 PHP Code Sample (If Applicable)

```php
    /** @param array<array-key, mixed> $configuration */
    private function streamIncomeStatement(array $configuration, IncomeStatement $incomeStatement): Response
    {
        return new StreamedJsonResponse([
            'net_income' => [
                'currency' => 'USD',
                'amount' => $incomeStatement->getNetIncome()->getAmount(),
            ],
            'accounts' => isset($configuration['remove_zero_amount_cost_centres']) && Type\bool()->assert($configuration['remove_zero_amount_cost_centres']) ? $incomeStatement->getNonZeroResults() : $incomeStatement->getResults(),
        ]);
    }
```

### 🖥️ Operating System

osx

### 📦 How did you install Mago?

composer
