### ISSUE TITLE
formatter: some arrays not being formatter as tables

### ISSUE THREAD

**Issue by bendavies** [carthage-software/mago#159]
### 🐞 Describe the Bug

I can't see any obvious reason why the following fail to be aligned.

not included in code example, but i don't think the table formatting respects the configured `print_width`?

### 🔄 Steps to Reproduce

mago fmt

### ⚙️ Configuration (mago.toml)

```toml
# Mago configuration file
# For more information, see https://mago.carthage.software/#/getting-started/configuration
php_version = "8.3.0"

[source]
paths = ["src", "tests"]
includes = ["vendor"]
excludes = []

[format]
print_width = 1800
tab_width = 4
use_tabs = false
space_around_concatenation_binary_operator = false
space_before_arrow_function_parameter_list_parenthesis = true
parentheses_in_attribute = true
null_type_hint = "question"

preserve_breaking_member_access_chain = true
preserve_breaking_argument_list = true
preserve_breaking_array_like = true
preserve_breaking_parameter_list = true
preserve_breaking_attribute_list = true
preserve_breaking_conditional_expression = true

[linter]
default_plugins = true
plugins = ["symfony", "php-unit"]
```

### 📜 Command Output

```shell
n/a
```

### 📂 PHP Code Sample (If Applicable)

```php
$a = [
    ['2017', '$0.00', '$0.00', '$0.00', '$0.00', '$0.00', '$0.00', '$0.00', '$0.00', '$0.00', '$0.00', '$0.00', '$0.00', '$0.00'],
    ['2016', '$0.00', '$0.00', '$0.00', '$0.00', '$0.00', '$0.00', '$0.00', '$0.00', '$0.00', '$0.00', '$0.00', '$0.00', '$101.00'],
    ['Growth', '0%', '0%', '0%', '0%', '0%', '0%', '0%', '0%', '0%', '0%', '0%', '0%', '-100%'],
];

$b = [
    ['', 'Name', 'Description'],
    ['', 'Name', 'Description'],
    ['', 'The name', 'The description'],
];

$c = [
    ['Policy Premium', '$741.00'],
    ['Policy Fee', '$200.00'],
    ['Inspection Fee', '$150.00'],
    ['Surplus Lines Tax', '$26.73'],
    ['Stamping Fee', '$1.60'],
];

$d = [
    ['Unique ID', 'BindHQ ID', 'State', 'Message', ''],
    ['-', HtmlValue::regexp('/^\d+$/'), 'Ready', '~', 'Message × ~ Close View full Message'],
    ['-', HtmlValue::regexp('/^\d+$/'), 'Ready', '~', 'Message × ~ Close View full Message'],
];
```

### 🖥️ Operating System

Linux

### 📦 How did you install Mago?

Homebrew (brew install mago)
