### ISSUE TITLE
`preserve_breaking_member_access_chain` is not respected

### ISSUE THREAD

**Issue by innocenzi** [carthage-software/mago#160]
![Image](https://github.com/user-attachments/assets/97f38b3b-ea2f-4c2f-99a0-602bf5263529)

**Before**
```php
expect($response->dto()->get(2))
    ->id->toBe(21)
    ->name->toBe('Payslips')
    ->files->toHaveCount(1)
    ->files->first()->toBeInstanceOf(FileData::class);
```

**After**
```php
expect($response->dto()->get(2))
    ->id
    ->toBe(21)
    ->name
    ->toBe('Payslips')
    ->files
    ->toHaveCount(1)
    ->files
    ->first()
    ->toBeInstanceOf(FileData::class);
```

Using Mago v0.20.2:

```toml
[format]
print_width = 180
tab_width = 4
use_tabs = false
null_type_hint = "question"
space_before_arrow_function_parameter_list_parenthesis = true
space_after_logical_not_unary_prefix_operator = true
always_break_named_arguments_list = false
preserve_breaking_member_access_chain = true
preserve_breaking_argument_list = true
preserve_breaking_array_like = true
preserve_breaking_parameter_list = true
preserve_breaking_attribute_list = true
preserve_breaking_conditional_expression = true
```
