### ISSUE TITLE
`preserve_breaking_parameter_list` is not respected

### ISSUE THREAD

**Issue by innocenzi** [carthage-software/mago#161]
![Image](https://github.com/user-attachments/assets/0e695dd5-b530-4991-b91f-a78cb7d84631)

**Before**

```php
File::query()->upsert(
    values: array_map(fn (UploadableFileData $file) => [
        'batch_id' => $batch->id,
        'file_id' => $file->id,
        'file_name' => $file->filename,
        'status' => Status::PROCESSING,
    ], $files),
    uniqueBy: ['id'],
);
```

**After**

```php
File::query()->upsert(
    values: array_map(
        fn (UploadableFileData $file) => [
            'batch_id' => $batch->id,
            'file_id' => $file->id,
            'file_name' => $file->filename,
            'status' => Status::PROCESSING,
        ],
        $files,
    ),
    uniqueBy: ['id'],
);
```

Using Mago v0.20.2:
```toml
[format]
print_width = 180
tab_width = 4
use_tabs = false
null_type_hint = "question"
space_before_arrow_function_parameter_list_parenthesis = true
space_after_logical_not_unary_prefix_operator = true
always_break_named_arguments_list = false
preserve_breaking_member_access_chain = true
preserve_breaking_argument_list = true
preserve_breaking_array_like = true
preserve_breaking_parameter_list = true
preserve_breaking_attribute_list = true
preserve_breaking_conditional_expression = true
array_table_style_alignment = false
```
