### ISSUE TITLE
Member chaining regressions since v0.20.2

### ISSUE THREAD

**Issue by innocenzi** [carthage-software/mago#162]
**Before**

```php
$timesOff = $this->bamboo
    ->send(new TimeOffRequest(from: $from, to: $to))
    ->collect();
```

**After**

```php
$timesOff = $this->bamboo->send(new TimeOffRequest(from: $from, to: $to))->collect();
```

---

**Before**

```php
expect(config('filesystems.disks.' . Disk::BASE_NAME))
    ->toBeArray()
    ->host->not->toBeNull();
```

**After**

```php
expect(config('filesystems.disks.' . Disk::BASE_NAME))
    ->toBeArray()
    ->host
    ->not->toBeNull();
```

---

**Before**

```php
public function context(): array
{
    return [
        'http_code' => $this->response->status(),
        'request_body' => $this->response
            ->getPsrRequest()
            ->getBody()
            ->__toString(),
        'response_body' => $this->response->body(),
        'original_exception_message' => $this->originalException?->getMessage(),
        'original_exception_serialized' => $this->originalException?->__toString(),
    ];
}
```

**After**

```php
public function context(): array
{
    return [
        'http_code' => $this->response->status(),
        'request_body' => $this->response->getPsrRequest()->getBody()->__toString(),
        'response_body' => $this->response->body(),
        'original_exception_message' => $this->originalException?->getMessage(),
        'original_exception_serialized' => $this->originalException?->__toString(),
    ];
}
```

---

**Before**

```php
expect($response->dto())
    ->toBeInstanceOf(LegData::class)
    ->flight_number
    ->toBe('FSF492J')
    ->tail_number
    ->toBe('OH-TUA')
    ->arrives_at
    ->toBeInstanceOf(Carbon\CarbonImmutable::class)
    ->arrives_at
    ->equalTo('2024-05-14 13:55:00')
    ->toBeTrue();
```

**After**

```php
expect($response->dto())
    ->toBeInstanceOf(LegData::class)
    ->flight_number->toBe('FSF492J')
    ->tail_number->toBe('OH-TUA')
    ->arrives_at->toBeInstanceOf(Carbon\CarbonImmutable::class)
    ->arrives_at->equalTo('2024-05-14 13:55:00')->toBeTrue();
```

---

**Before**

```php
expect($response->json())
    ->ok->toBeTrue()
    ->channel->toBe('C08CL4QQH8F')
    ->message->text->toBe('Hello world');
```

**After**

```php
expect($response->json())
    ->ok->toBeTrue()
    ->channel->toBe('C08CL4QQH8F')
    ->message
    ->text->toBe('Hello world');
```

---

**Before**

```php
$this->connector
    ->pool(
        requests: $legs->map(fn (int $legId) => new GetLegRequest($legId)),
        responseHandler: function (Response $response) use (&$passengers) {
            $passengers = [
                ...($passengers ?? []),
                ...$response->json('Pax'),
            ];
        },
    )
    ->send()
    ->wait();
```

**After**

```php
$this->connector->pool(
        requests: $legs->map(fn (int $legId) => new GetLegRequest($legId)),
        responseHandler: function (Response $response) use (&$passengers) {
            $passengers = [
                ...($passengers ?? []),
                ...$response->json('Pax'),
            ];
        },
    )->send()->wait();
```

---

These are diffs between Mago v0.20.2 and v0.20.3 using:

```toml
php_version = "8.4.0"

[source]
paths = ["src"]
includes = ["vendor"]
excludes = ["./vendor/composer", "./vendor/symfony"]

[format]
print_width = 180
tab_width = 4
use_tabs = false
null_type_hint = "question"
space_before_arrow_function_parameter_list_parenthesis = true
space_after_logical_not_unary_prefix_operator = true
always_break_named_arguments_list = false
preserve_breaking_member_access_chain = true
preserve_breaking_argument_list = true
preserve_breaking_array_like = true
preserve_breaking_parameter_list = true
preserve_breaking_attribute_list = true
preserve_breaking_conditional_expression = true
array_table_style_alignment = false
```
