### ISSUE TITLE
Variable assignation goes on a new line

### ISSUE THREAD

**Issue by innocenzi** [carthage-software/mago#165]
I've got a few instances of variable assignation wrapping to a new line:

**Before**
```php
private function getCurrentLineIndex(): int
{
    $linePositions = $this->getLinePositions();

    foreach ($linePositions as $index => $startPosition) {
        $nextPosition = ($index + 1) < count($linePositions)
            ? $linePositions[$index + 1]
            : (mb_strlen($this->text) + 1);

        if ($this->cursor >= $startPosition && $this->cursor < $nextPosition) {
            return $index;
        }
    }

    return count($linePositions) - 1; // Default to last line if not found
}
```

**After**
```php
private function getCurrentLineIndex(): int
{
    $linePositions = $this->getLinePositions();

    foreach ($linePositions as $index => $startPosition) {
        $nextPosition =
            ($index + 1) < count($linePositions)
                ? $linePositions[$index + 1]
                : (mb_strlen($this->text) + 1);

        if ($this->cursor >= $startPosition && $this->cursor < $nextPosition) {
            return $index;
        }
    }

    return count($linePositions) - 1; // Default to last line if not found
}
```

---

**Before**
```php
return [
    ...$controls,
    '↑' => 'up',
    '↓' => 'down',
    'enter' => $this->multiple && $this->default && $this->options->getSelectedOptions() === []
        ? 'skip'
        : 'confirm',
    'ctrl+c' => 'cancel',
];
```

**After**
```php
return [
    ...$controls,
    '↑' => 'up',
    '↓' => 'down',
    'enter' =>
        $this->multiple && $this->default && $this->options->getSelectedOptions() === []
            ? 'skip'
            : 'confirm',
    'ctrl+c' => 'cancel',
];
```

---

```toml
[format]
print_width = 180
tab_width = 4
use_tabs = false
null_type_hint = "question"
space_before_arrow_function_parameter_list_parenthesis = true
space_after_logical_not_unary_prefix_operator = true
always_break_named_arguments_list = false
preserve_breaking_member_access_chain = true
preserve_breaking_argument_list = true
preserve_breaking_array_like = true
preserve_breaking_parameter_list = true
preserve_breaking_attribute_list = true
preserve_breaking_conditional_expression = true
```
