### ISSUE TITLE
Attributes are being inconsistently set on the same line as the parameter

### ISSUE THREAD

**Issue by innocenzi** [carthage-software/mago#166]
**Before**
```php
#[ConsoleCommand]
public function test(
    #[ConsoleArgument]
    ?int $optionalValue = null,
    #[ConsoleArgument(name: 'custom-flag')]
    bool $flag = false,
): void
```

**After**
```php
#[ConsoleCommand]
public function test(
    #[ConsoleArgument] ?int $optionalValue = null,
    #[ConsoleArgument(name: 'custom-flag')]
    bool $flag = false,
): void 
```

---

**Before**
```php
public function __construct(
    #[Eager]
    public BWithEager $b,
) {
}
```

**After**
```php
public function __construct(
    #[Eager] public BWithEager $b,
) {
}
```

---

```toml
[format]
print_width = 180
tab_width = 4
use_tabs = false
null_type_hint = "question"
space_before_arrow_function_parameter_list_parenthesis = true
space_after_logical_not_unary_prefix_operator = true
always_break_named_arguments_list = false
preserve_breaking_member_access_chain = true
preserve_breaking_argument_list = true
preserve_breaking_array_like = true
preserve_breaking_parameter_list = true
preserve_breaking_attribute_list = true
preserve_breaking_conditional_expression = true
```
