### ISSUE TITLE
Empty anonymous class' curly braces get a new line

### ISSUE THREAD

**Issue by innocenzi** [carthage-software/mago#167]
**Before**
```php
public function test_unknown_handler_throws_exception(): void
{
    $this->expectException(CommandHandlerNotFound::class);

    command(new class () {});
}
```

**After**
```php
public function test_unknown_handler_throws_exception(): void
{
    $this->expectException(CommandHandlerNotFound::class);

    command(new class() {
    });
}
```

---

```toml
[format]
print_width = 180
tab_width = 4
use_tabs = false
null_type_hint = "question"
space_before_arrow_function_parameter_list_parenthesis = true
space_after_logical_not_unary_prefix_operator = true
always_break_named_arguments_list = false
preserve_breaking_member_access_chain = true
preserve_breaking_argument_list = true
preserve_breaking_array_like = true
preserve_breaking_parameter_list = true
preserve_breaking_attribute_list = true
preserve_breaking_conditional_expression = true
```
