### ISSUE TITLE
Function opening brace gets moved to the same line as the definition

### ISSUE THREAD

**Issue by innocenzi** [carthage-software/mago#171]
This one is weird. Uncommenting the `TestWith` attributes makes Mago format this snippet as expected :p 

**Before**
```php
#[TestWith(['foo_bar', '_bar', 'foo'])]
#[TestWith(['foo.bar/', '/', 'foo.bar'])]
// #[TestWith(['foo.bar/', ['/', 'bar/'], 'foo.bar'])]
// #[TestWith(['foo.bar/', ['bar/', '/'], 'foo.'])]
public function test_strip_end(string $input, string|array $strip, string $output): void
{
    $this->assertEquals($output, str($input)->stripEnd($strip)->toString());
}
```

**After**
```php
#[TestWith(['foo_bar', '_bar', 'foo'])]
#[TestWith(['foo.bar/', '/', 'foo.bar'])]
// #[TestWith(['foo.bar/', ['/', 'bar/'], 'foo.bar'])]
// #[TestWith(['foo.bar/', ['bar/', '/'], 'foo.'])]
public function test_strip_end(string $input, string|array $strip, string $output): void {
    $this->assertEquals($output, str($input)->stripEnd($strip)->toString());
}
```

**Config**
```toml
[format]
print_width = 180
tab_width = 4
use_tabs = false
space_after_logical_not_unary_prefix_operator = true
null_type_hint = "question"
space_before_arrow_function_parameter_list_parenthesis = true
always_break_named_arguments_list = false
preserve_breaking_member_access_chain = true
preserve_breaking_argument_list = true
preserve_breaking_array_like = true
preserve_breaking_parameter_list = true
preserve_breaking_attribute_list = true
preserve_breaking_conditional_expression = true
empty_line_after_opening_tag = false
```
