### ISSUE TITLE
Unwanted new line when using short ternary in a `match`

### ISSUE THREAD

**Issue by innocenzi** [carthage-software/mago#197]
### 🐞 Describe the Bug

The following snippet:

```php
private function renderErrorResponse(Status $status, ?HttpException $exception = null): GenericResponse
{
    return new GenericResponse(
        status: $status,
        body: new GenericView(__DIR__ . '/HttpErrorResponse/error.view.php', [
            'css' => $this->getCss(),
            'status' => $status->value,
            'title' => $status->description(),
            'message' => $exception?->getMessage() ?: match ($status) {
                Status::INTERNAL_SERVER_ERROR => 'An unexpected server error occurred',
                Status::NOT_FOUND => 'This page could not be found on the server',
                Status::FORBIDDEN => 'You do not have permission to access this page',
                Status::UNAUTHORIZED => 'You must be authenticated in to access this page',
                default => null,
            },
        ]),
    );
}
```

Gets formatted like this:

```php
private function renderErrorResponse(Status $status, ?HttpException $exception = null): GenericResponse
{
    return new GenericResponse(
        status: $status,
        body: new GenericView(__DIR__ . '/HttpErrorResponse/error.view.php', [
            'css' => $this->getCss(),
            'status' => $status->value,
            'title' => $status->description(),
            'message' =>
                $exception?->getMessage() ?: match ($status) {
                    Status::INTERNAL_SERVER_ERROR => 'An unexpected server error occurred',
                    Status::NOT_FOUND => 'This page could not be found on the server',
                    Status::FORBIDDEN => 'You do not have permission to access this page',
                    Status::UNAUTHORIZED => 'You must be authenticated in to access this page',
                    default => null,
                }
            ,
        ]),
    );
}
```

The new line is not necessary, and the coma gets its own line as well.

### 🔄 Steps to Reproduce

See the description.

### ⚙️ Configuration (mago.toml)

```toml
php_version = "8.4.0"

[source]
paths = ["src", "packages", "tests"]
includes = ["vendor"]
excludes = [
  "./vendor/symfony/cache/Traits/ValueWrapper.php",
  "./vendor/google/common-protos/metadata",
  "./vendor/google/gax/metadata",
  "./vendor/google/longrunning/metadata",
  "./vendor/composer",
  "**/.cache",
  "**/*.stub.php",
]

[format]
print_width = 180
tab_width = 4
use_tabs = false
space_after_logical_not_unary_prefix_operator = true
null_type_hint = "question"
space_before_arrow_function_parameter_list_parenthesis = true
always_break_named_arguments_list = false
preserve_breaking_member_access_chain = true
preserve_breaking_argument_list = true
preserve_breaking_array_like = true
preserve_breaking_parameter_list = true
preserve_breaking_attribute_list = true
preserve_breaking_conditional_expression = true
empty_line_after_opening_tag = false
```

### 📜 Command Output

```shell
Irrelevant.
```

### 📂 PHP Code Sample (If Applicable)

```php

```

### 🖥️ Operating System

macOS

### 📦 How did you install Mago?

Composer (`composer require carthage-software/mago`)
