### ISSUE TITLE
Unwanted new line on method with two arguments

### ISSUE THREAD

**Issue by innocenzi** [carthage-software/mago#198]
**Before**

```php
$this->container->singleton(ResponseSender::class, fn () => new class($this) implements ResponseSender {
    public function __construct(
        private HttpExceptionHandlerTest $case,
    ) {}

    public function send(Response $response): Response
    {
        $this->case->response = $response;

        return $response;
    }
});
```

**After**

```php
$this->container->singleton(
    ResponseSender::class,
    fn () => new class($this) implements ResponseSender {
        public function __construct(
            private HttpExceptionHandlerTest $case,
        ) {}

        public function send(Response $response): Response
        {
            $this->case->response = $response;

            return $response;
        }
    },
);
```

**Config**

```toml
php_version = "8.4.0"

[source]
paths = ["src", "packages", "tests"]
includes = ["vendor"]
excludes = [
  "./vendor/symfony/cache/Traits/ValueWrapper.php",
  "./vendor/google/common-protos/metadata",
  "./vendor/google/gax/metadata",
  "./vendor/google/longrunning/metadata",
  "./vendor/composer",
  "**/.cache",
  "**/*.stub.php",
]

[format]
print_width = 180
tab_width = 4
use_tabs = false
space_after_logical_not_unary_prefix_operator = true
null_type_hint = "question"
space_before_arrow_function_parameter_list_parenthesis = true
always_break_named_arguments_list = false
preserve_breaking_member_access_chain = true
preserve_breaking_argument_list = true
preserve_breaking_array_like = true
preserve_breaking_parameter_list = true
preserve_breaking_attribute_list = true
preserve_breaking_conditional_expression = true
empty_line_after_opening_tag = false
```
