### ISSUE TITLE
[Linter] easily enable only a single rule from a plugin

### ISSUE THREAD

**Issue by bendavies** [carthage-software/mago#210]
### 🚀 Describe the Feature

I want to gradually introduce the linter to our codebase.
To make this easier, i want to only enable a single rule from a plugin, rather than disabling everything i don't want.

For example, if I only want `strictness/require-strict-types` for now, i need to do:

```toml
[linter]
default_plugins = false
plugins = ["strictness"]

[[linter.rules]]
name = "strictness/require-strict-types"
level = "error"

[[linter.rules]]
name = "strictness/require-return-type"
level = "off"

[[linter.rules]]
name = "strictness/require-constant-type"
level = "off"

[[linter.rules]]
name = "strictness/require-property-type"
level = "off"

[[linter.rules]]
name = "strictness/no-shorthand-ternary"
level = "off"

[[linter.rules]]
name = "strictness/no-assignment-in-condition"
level = "off"

[[linter.rules]]
name = "strictness/require-parameter-type"
level = "off"

[[linter.rules]]
name = "strictness/missing-assert-description"
level = "off"

[[linter.rules]]
name = "strictness/no-empty-construct"
level = "off"

[[linter.rules]]
name = "strictness/require-identity-comparison"
level = "off"

[[linter.rules]]
name = "strictness/require-strict-behavior"
level = "off"
```

### ✅ Use Case / Example

Smaller, easier to read configuration.

### 💡 Proposed Solution

something like this would be easier:

```toml
[linter]
default_plugins = false
plugins = ["strictness"]

# defaults:
[[linter]]
name = "strictness"
level = "off"

[[linter.rules]]
name = "strictness/require-strict-types"
level = "error"
```

### 📌 Priority

Nice to have
