### ISSUE TITLE
Code after __halt_compiler() should not be parserd

### ISSUE THREAD

**Issue by lyrixx** [carthage-software/mago#214]
### 🐞 Describe the Bug

A \n is added where it should not 

### 🔄 Steps to Reproduce

```diff
-__halt_compiler();<?php

+__halt_compiler();
+<?php
+
```

### ⚙️ Configuration (mago.toml)

```toml
# Mago configuration file
# For more information, see https://mago.carthage.software/#/getting-started/configuration
php_version = "8.4.0"

[source]
paths = ["src/", "tests/"]
includes = ["vendor"]
excludes = []

[format]
print_width = 120
tab_width = 4
use_tabs = false

[linter]
default_plugins = true
plugins = ["symfony", "php-unit"]
```

### 📜 Command Output

```shell
See above
```

### 📂 PHP Code Sample (If Applicable)

```php

```

### 🖥️ Operating System

Linux

### 📦 How did you install Mago?

Prebuilt Binary (download from GitHub)
