### ISSUE TITLE
Formatting double quote string with escaped double quotes results in syntax error

### ISSUE THREAD

**Issue by innocenzi** [carthage-software/mago#221]
**Before**
```php
$this->writeln("<style=\"bg-red fg-white\"><{$date->format('Y-m-d H:i:s')} </style> {$event->url} (throttled)");
```

**After**
```php
$this->writeln("<style="bg-red fg-white"><{$date->format('Y-m-d H:i:s')} </style> {$event->url} (throttled)");
```

**Config**
Mago 0.25.0

```toml
php_version = "8.4.0"

[source]
paths = ["src"]
includes = ["vendor"]
excludes = [
	"./vendor/symfony/cache/Traits/ValueWrapper.php",
	"./vendor/composer",
]

[format]
print_width = 180
tab_width = 4
use_tabs = false
space_after_logical_not_unary_prefix_operator = true
null_type_hint = "question"
space_before_arrow_function_parameter_list_parenthesis = true
always_break_named_arguments_list = false
preserve_breaking_member_access_chain = true
preserve_breaking_argument_list = true
preserve_breaking_array_like = true
preserve_breaking_parameter_list = true
preserve_breaking_attribute_list = true
preserve_breaking_conditional_expression = true
empty_line_after_opening_tag = false
```
