### ISSUE TITLE
Doesn't respect formatting configuration

### ISSUE THREAD

**Issue by LinusU** [carthage-software/mago#41]
I'm having problems getting mago to pick up my formatter configuration.

This is my `mago.toml`:

```toml
[source]
paths = ["b.php"]

[formatter]
print_width = 200
tab_width = 4
use_tabs = true
trailing_comma = true
function_brace_style = "same_line"
method_brace_style = "same_line"
classlike_brace_style = "same_line"
type_spacing = 1
```

I can see that the config file is being read, because when I run `mago format --dry-run` it only shows modifications to `b.php`, and not `a.php`. However, `use_tabs`, `classlike_brace_style`, etc. is not being respected.

I've tried this with the current HEAD (36d9c70), installed via `cargo install mago --git https://github.com/carthage-software/mago`.

The issue was also present in 0.0.20 installed via Homebrew.

Thanks for working on this tool! 🙏
